"""Matrix theme — declarative element registry for HyprConfig.

Every themeable element is a SELECTOR: a setting with named values, exactly one
of which is always the untouched "base" (your current look). The visible desktop
is fully described by the selector values stored in state.json['theme']. There is
no snapshot and no restore: switching an element back to its base value simply
re-points the selector at a variant that was never mutated.

Layer rule (hard constraint): BOOT / LOCK / SHELL-chrome / borders may
carry the Matrix aesthetic; application windows are NEVER tinted.

This module holds the Matrix variant data and the per-element activate() logic.
It imports theming.py lazily (inside functions) to avoid an import cycle — the
Theming page imports this module at load time to build the selector UI.
"""

import subprocess

from .parser import (get_theme, set_theme, hyprctl_set, hyprctl_reload,
                     persist_borders)
from .paths import HYPR_DIR, XDG_CONFIG_HOME
from .safe_io import atomic_symlink, atomic_write_text, remove_with_backup

# ── Canonical Matrix palette ────────────────────────────────────────────────
# Vampire Black / Dark Green / Islam Green / Erin. Desaturated field, bright
# glyphs. Keys match what theming.write_rofi_colors / write_waybar_theme expect.
MATRIX_PALETTE = {
    'bg':       '#0D0208',   # vampire black
    'bg_alt':   '#003B00',   # dark green (surface container)
    'fg':       '#00FF41',   # erin — bright code
    'fg_dim':   '#008F11',   # islam green
    'accent':   '#00FF41',
    'accent2':  '#008F11',
    'tertiary': '#00FF41',
    'surface':  '#0D0208',   # waybar bar-bg base
}
MATRIX_BORDER_ACTIVE = 'rgba(00ff41ff) rgba(008f11ff) 45deg'
MATRIX_BORDER_INACTIVE = 'rgba(003b00aa)'

# ── dunst: palette colors delivered via an auto-loaded drop-in ──────────────
# dunst (>=1.7) reads ~/.config/dunst/dunstrc.d/*.conf after dunstrc, later
# definitions overriding earlier. Only the matrix mode writes a drop-in; base
# modes remove it so the untouched, hand-authored dunstrc governs colors.
DUNST_DROPIN = (XDG_CONFIG_HOME / 'dunst' / 'dunstrc.d'
                / 'zzz-hyprconfig-matrix.conf')

MATRIX_DUNST = '''# Matrix palette — generated by HyprConfig (declarative theme selector).
# Auto-loaded after dunstrc; delete or switch palette off Matrix to revert.
# The base dunstrc is never modified.
[urgency_low]
    background = "#0D0208ee"
    foreground = "#008F11"
    frame_color = "#008F1180"
    highlight = "#00FF41"

[urgency_normal]
    background = "#0D0208ee"
    foreground = "#00FF41"
    frame_color = "#00FF4180"
    highlight = "#00FF41"

[urgency_critical]
    background = "#1A0A00ee"
    foreground = "#FFB000"
    frame_color = "#FFB000"
    highlight = "#FFB000"
'''


def _reload_dunst():
    try:
        subprocess.run(['dunstctl', 'reload'], capture_output=True, timeout=3)
    except Exception:
        pass


def write_dunst_colors(mode):
    """Materialise (or clear) the dunst palette drop-in.

    mode == 'matrix'  -> write the green/amber drop-in.
    otherwise         -> remove it so the base dunstrc colors apply.
    The base dunstrc is never touched either way.
    """
    if mode == 'matrix':
        atomic_write_text(DUNST_DROPIN, MATRIX_DUNST)
    else:
        try:
            remove_with_backup(DUNST_DROPIN)
        except Exception:
            pass
    _reload_dunst()


def apply_matrix_palette():
    """Push the Matrix greens through every themed surface (chrome only)."""
    from . import theming as t
    hyprctl_set('general:col.active_border', MATRIX_BORDER_ACTIVE)
    hyprctl_set('general:col.inactive_border', MATRIX_BORDER_INACTIVE)
    persist_borders(MATRIX_BORDER_ACTIVE, MATRIX_BORDER_INACTIVE)
    t.write_rofi_colors(MATRIX_PALETTE)
    t.write_waybar_theme(MATRIX_PALETTE)
    t.write_fish_colors(MATRIX_PALETTE)
    write_dunst_colors('matrix')
    return MATRIX_PALETTE


# ── Element activation ──────────────────────────────────────────────────────

def _activate_palette(value):
    """palette selector: matugen | gold | matrix. All lossless + live."""
    from . import theming as t
    if value == 'matrix':
        apply_matrix_palette()
    elif value == 'gold':
        t.apply_gold_palette()
        write_dunst_colors('gold')
    else:  # matugen — regenerate today's look from the wallpaper
        t.regenerate_theme_from_wallpaper()
        write_dunst_colors('matugen')
    t.restart_waybar()


ANIMATIONS_CONF = HYPR_DIR / 'animations.conf'


def _activate_animations(value):
    """animations selector: rewrite $ANIMATION_PATH (the HyDE mechanism).

    Base preset files are never edited; only the one-line pointer changes, then
    Hyprland reloads. `value` is a preset name (e.g. 'theme', 'matrix').
    """
    try:
        if not ANIMATIONS_CONF.exists():
            return
        import re
        text = ANIMATIONS_CONF.read_text()
        new = re.sub(r'(\$ANIMATION_PATH\s*=\s*)\./animations/[^\n]*',
                     r'\1./animations/%s.conf' % value, text, count=1)
        if new != text:
            atomic_write_text(ANIMATIONS_CONF, new)
        hyprctl_reload()
    except Exception:
        pass


HYPRLOCK_ACTIVE = HYPR_DIR / 'hyprlock-active.conf'
_LOCK_VARIANT_FILE = {
    'base':   'hyprlock-default.conf',
    'matrix': 'hyprlock-matrix.conf',
}


def _activate_lock(value):
    """lock selector: relink hyprlock-active.conf at the chosen variant.

    hyprlock.conf is a pointer that sources hyprlock-active.conf, so bare
    `hyprlock` (hypridle / keybind / watchdog — all untouched) picks up the
    selected variant on the next lock. Base variant files are never edited.
    Mirrors the animations.conf $ANIMATION_PATH indirection.
    """
    target = _LOCK_VARIANT_FILE.get(value, _LOCK_VARIANT_FILE['base'])
    try:
        if not (HYPR_DIR / target).exists():
            return
        # Relative symlink target keeps it portable within ~/.config/hypr.
        atomic_symlink(HYPRLOCK_ACTIVE, target)
    except Exception:
        pass


# ── Element registry ────────────────────────────────────────────────────────
# Each entry describes one selector. Optional selectors declare an availability
# check and are omitted when their local integration files do not exist.
ELEMENTS = {
    'palette': {
        'title': 'Palette',
        'subtitle': 'Borders, rofi, waybar, dunst, fish colors',
        'values': [('matugen', 'Material You'),
                   ('gold', 'Classic Gold'),
                   ('matrix', 'Matrix Green')],
        'base': 'matugen',
        'matrix': 'matrix',
        'live': True,
        'activate': _activate_palette,
    },
    'animations': {
        'title': 'Animations',
        'subtitle': 'Window open/close/workspace motion preset',
        'values': [('theme', 'Theme Preference'),
                   ('matrix', 'Matrix (digital glitch)')],
        'base': 'theme',
        'matrix': 'matrix',
        'live': True,
        'available': lambda: ANIMATIONS_CONF.exists(),
        'activate': _activate_animations,
    },
    'lock': {
        'title': 'Lock screen',
        'subtitle': 'Green field, live clock — via hyprlock variant pointer',
        'values': [('base', 'System default'), ('matrix', 'Matrix')],
        'base': 'base',
        'matrix': 'matrix',
        'live': True,
        'available': lambda: all((HYPR_DIR / name).exists()
                                for name in _LOCK_VARIANT_FILE.values()),
        'activate': _activate_lock,
    },
}


def visible_elements():
    """Return selectors whose required local configuration is available."""
    return {
        key: element for key, element in ELEMENTS.items()
        if not element.get('available') or element['available']()
    }


def set_element(key, value):
    """Record a selector value and activate its variant live (if wired)."""
    set_theme(key, value)
    el = ELEMENTS.get(key)
    if el and el.get('live') and el.get('activate'):
        el['activate'](value)


def apply_all():
    """Re-activate every live element from its current selector value.

    With all selectors at base, this reproduces today's exact look — the proof
    that 'current' is just a configuration you can pick, not a backup.
    """
    for key, el in visible_elements().items():
        if el.get('live') and el.get('activate'):
            try:
                el['activate'](get_theme(key))
            except Exception:
                pass


def set_all_matrix():
    """Convenience: flip every LIVE element to its Matrix value."""
    for key, el in visible_elements().items():
        if el.get('live'):
            set_element(key, el['matrix'])


def set_all_current():
    """Convenience: flip every LIVE element back to its base value."""
    for key, el in visible_elements().items():
        if el.get('live'):
            set_element(key, el['base'])
